sources:
  - Marhey.glyphs
axisOrder:
  - wght
familyName: Marhey
stat:
  Marhey-VF.ttf:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800