sources:
  - Marhey.glyphs
axisOrder:
  - wght
familyName: Marhey
stat:
  Marhey[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 425
      linkedValue: 675
      flags: 2
    - name: SemiBold
      value: 550
    - name: Bold
      value: 675
    - name: ExtraBold
      value: 800
